# 数据库配置信息
database:
  default:
    host:
    port: 3306
    username:
    password:
    name:

# 电子邮件配置信息
email:
  smtp:
    host: smtp.163.com
    port: 25
    username:
    password:

# session配置信息
session:
  type: cookie
  secret: 1234567890
  # session 过期时间
  max_age: 72000
  cookie:
    name: ice_flame
  redis:
    name: ice_flame
    address: localhost:6379
    db: 0
    password: ""
    prefix_length: 10
    network: "tcp"
  memcached:
    name: ice_flame
    address: localhost:11211

