// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUcAccount = "uc_account"

// UcAccount 用户中心
type UcAccount struct {
	ID             uint32    `gorm:"column:id;type:int(10) unsigned;primaryKey;autoIncrement:true" json:"id"`
	IdentityCardID *string   `gorm:"column:identity_card_id;type:char(18);index:identity_card_id,priority:1;default:0;comment:关联用户身份证信息ID" json:"identity_card_id"` // 关联用户身份证信息ID
	Username       string    `gorm:"column:username;type:char(40);comment:用户名" json:"username"`                                                                     // 用户名
	PasswordHash   string    `gorm:"column:password_hash;type:char(60);comment:用户密码" json:"password_hash"`                                                          // 用户密码
	Tel            string    `gorm:"column:tel;type:char(20);comment:用户手机号码" json:"tel"`                                                                            // 用户手机号码
	Status         uint32    `gorm:"column:status;type:tinyint(2) unsigned;comment:用户状态(0.启用1.停用)" json:"status"`                                                   // 用户状态(0.启用1.停用)
	RealNameType   *uint32   `gorm:"column:real_name_type;type:tinyint(2) unsigned;default:1;comment:实名状态1=未实名2=已上传未审核3=审核驳回4=实名成功" json:"real_name_type"`          // 实名状态1=未实名2=已上传未审核3=审核驳回4=实名成功
	CreatedAt      time.Time `gorm:"column:created_at;type:datetime" json:"created_at"`
	UpdatedAt      time.Time `gorm:"column:updated_at;type:datetime" json:"updated_at"`
}

// TableName UcAccount's table name
func (*UcAccount) TableName() string {
	return TableNameUcAccount
}
