// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUcSystemMasterRole = "uc_system_master_role"

// UcSystemMasterRole 管理员角色表
type UcSystemMasterRole struct {
	ID           uint32    `gorm:"column:id;type:int unsigned;primaryKey;autoIncrement:true;comment:自增ID" json:"id"` // 自增ID
	Name         string    `gorm:"column:name;type:varchar(30);comment:角色名称" json:"name"`                            // 角色名称
	Remark       string    `gorm:"column:remark;type:varchar(100);comment:备注" json:"remark"`                         // 备注
	SupperMaster bool      `gorm:"column:supper_master;type:tinyint(1);comment:1为超级管理员模块" json:"supper_master"`      // 1为超级管理员模块
	CreatedAt    time.Time `gorm:"column:created_at;type:datetime" json:"created_at"`
	UpdatedAt    time.Time `gorm:"column:updated_at;type:datetime" json:"updated_at"`
}

// TableName UcSystemMasterRole's table name
func (*UcSystemMasterRole) TableName() string {
	return TableNameUcSystemMasterRole
}
