// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUcSystemMasterVisitorLog = "uc_system_master_visitor_logs"

// UcSystemMasterVisitorLog 管理员访问记录
type UcSystemMasterVisitorLog struct {
	ID            uint32    `gorm:"column:id;type:int unsigned;primaryKey;autoIncrement:true;comment:自增ID" json:"id"`                     // 自增ID
	AccountID     uint32    `gorm:"column:account_id;type:int unsigned;comment:关联用户ID" json:"account_id"`                                 // 关联用户ID
	OsCategory    uint32    `gorm:"column:os_category;type:tinyint unsigned;comment:系统访问类型（1=web端，2=android端，3=IOS端）" json:"os_category"` // 系统访问类型（1=web端，2=android端，3=IOS端）
	VisitCategory uint32    `gorm:"column:visit_category;type:smallint unsigned;comment:访问类型" json:"visit_category"`                      // 访问类型
	UnionID       uint32    `gorm:"column:union_id;type:int unsigned;comment:关联ID" json:"union_id"`                                       // 关联ID
	Description   string    `gorm:"column:description;type:varchar(100);comment:访问信息描述" json:"description"`                               // 访问信息描述
	IPLong        string    `gorm:"column:ip_long;type:varchar(16)" json:"ip_long"`
	IP            string    `gorm:"column:ip;type:varchar(47)" json:"ip"`
	CreatedAt     time.Time `gorm:"column:created_at;type:datetime" json:"created_at"`
	UpdatedAt     time.Time `gorm:"column:updated_at;type:datetime" json:"updated_at"`
}

// TableName UcSystemMasterVisitorLog's table name
func (*UcSystemMasterVisitorLog) TableName() string {
	return TableNameUcSystemMasterVisitorLog
}
