// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"ice_flame_gin/internal/app/models/model"
)

func newUcSystemMasterRoleRelation(db *gorm.DB, opts ...gen.DOOption) ucSystemMasterRoleRelation {
	_ucSystemMasterRoleRelation := ucSystemMasterRoleRelation{}

	_ucSystemMasterRoleRelation.ucSystemMasterRoleRelationDo.UseDB(db, opts...)
	_ucSystemMasterRoleRelation.ucSystemMasterRoleRelationDo.UseModel(&model.UcSystemMasterRoleRelation{})

	tableName := _ucSystemMasterRoleRelation.ucSystemMasterRoleRelationDo.TableName()
	_ucSystemMasterRoleRelation.ALL = field.NewAsterisk(tableName)
	_ucSystemMasterRoleRelation.ID = field.NewUint32(tableName, "id")
	_ucSystemMasterRoleRelation.AccountID = field.NewUint32(tableName, "account_id")
	_ucSystemMasterRoleRelation.RoleID = field.NewUint32(tableName, "role_id")
	_ucSystemMasterRoleRelation.CreatedAt = field.NewTime(tableName, "created_at")
	_ucSystemMasterRoleRelation.UpdatedAt = field.NewTime(tableName, "updated_at")

	_ucSystemMasterRoleRelation.fillFieldMap()

	return _ucSystemMasterRoleRelation
}

// ucSystemMasterRoleRelation 角色信息关联管理ID
type ucSystemMasterRoleRelation struct {
	ucSystemMasterRoleRelationDo ucSystemMasterRoleRelationDo

	ALL       field.Asterisk
	ID        field.Uint32
	AccountID field.Uint32 // 管理员ID
	RoleID    field.Uint32 // 身份ID
	CreatedAt field.Time
	UpdatedAt field.Time

	fieldMap map[string]field.Expr
}

func (u ucSystemMasterRoleRelation) Table(newTableName string) *ucSystemMasterRoleRelation {
	u.ucSystemMasterRoleRelationDo.UseTable(newTableName)
	return u.updateTableName(newTableName)
}

func (u ucSystemMasterRoleRelation) As(alias string) *ucSystemMasterRoleRelation {
	u.ucSystemMasterRoleRelationDo.DO = *(u.ucSystemMasterRoleRelationDo.As(alias).(*gen.DO))
	return u.updateTableName(alias)
}

func (u *ucSystemMasterRoleRelation) updateTableName(table string) *ucSystemMasterRoleRelation {
	u.ALL = field.NewAsterisk(table)
	u.ID = field.NewUint32(table, "id")
	u.AccountID = field.NewUint32(table, "account_id")
	u.RoleID = field.NewUint32(table, "role_id")
	u.CreatedAt = field.NewTime(table, "created_at")
	u.UpdatedAt = field.NewTime(table, "updated_at")

	u.fillFieldMap()

	return u
}

func (u *ucSystemMasterRoleRelation) WithContext(ctx context.Context) *ucSystemMasterRoleRelationDo {
	return u.ucSystemMasterRoleRelationDo.WithContext(ctx)
}

func (u ucSystemMasterRoleRelation) TableName() string {
	return u.ucSystemMasterRoleRelationDo.TableName()
}

func (u ucSystemMasterRoleRelation) Alias() string { return u.ucSystemMasterRoleRelationDo.Alias() }

func (u ucSystemMasterRoleRelation) Columns(cols ...field.Expr) gen.Columns {
	return u.ucSystemMasterRoleRelationDo.Columns(cols...)
}

func (u *ucSystemMasterRoleRelation) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := u.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (u *ucSystemMasterRoleRelation) fillFieldMap() {
	u.fieldMap = make(map[string]field.Expr, 5)
	u.fieldMap["id"] = u.ID
	u.fieldMap["account_id"] = u.AccountID
	u.fieldMap["role_id"] = u.RoleID
	u.fieldMap["created_at"] = u.CreatedAt
	u.fieldMap["updated_at"] = u.UpdatedAt
}

func (u ucSystemMasterRoleRelation) clone(db *gorm.DB) ucSystemMasterRoleRelation {
	u.ucSystemMasterRoleRelationDo.ReplaceConnPool(db.Statement.ConnPool)
	return u
}

func (u ucSystemMasterRoleRelation) replaceDB(db *gorm.DB) ucSystemMasterRoleRelation {
	u.ucSystemMasterRoleRelationDo.ReplaceDB(db)
	return u
}

type ucSystemMasterRoleRelationDo struct{ gen.DO }

func (u ucSystemMasterRoleRelationDo) Debug() *ucSystemMasterRoleRelationDo {
	return u.withDO(u.DO.Debug())
}

func (u ucSystemMasterRoleRelationDo) WithContext(ctx context.Context) *ucSystemMasterRoleRelationDo {
	return u.withDO(u.DO.WithContext(ctx))
}

func (u ucSystemMasterRoleRelationDo) ReadDB() *ucSystemMasterRoleRelationDo {
	return u.Clauses(dbresolver.Read)
}

func (u ucSystemMasterRoleRelationDo) WriteDB() *ucSystemMasterRoleRelationDo {
	return u.Clauses(dbresolver.Write)
}

func (u ucSystemMasterRoleRelationDo) Session(config *gorm.Session) *ucSystemMasterRoleRelationDo {
	return u.withDO(u.DO.Session(config))
}

func (u ucSystemMasterRoleRelationDo) Clauses(conds ...clause.Expression) *ucSystemMasterRoleRelationDo {
	return u.withDO(u.DO.Clauses(conds...))
}

func (u ucSystemMasterRoleRelationDo) Returning(value interface{}, columns ...string) *ucSystemMasterRoleRelationDo {
	return u.withDO(u.DO.Returning(value, columns...))
}

func (u ucSystemMasterRoleRelationDo) Not(conds ...gen.Condition) *ucSystemMasterRoleRelationDo {
	return u.withDO(u.DO.Not(conds...))
}

func (u ucSystemMasterRoleRelationDo) Or(conds ...gen.Condition) *ucSystemMasterRoleRelationDo {
	return u.withDO(u.DO.Or(conds...))
}

func (u ucSystemMasterRoleRelationDo) Select(conds ...field.Expr) *ucSystemMasterRoleRelationDo {
	return u.withDO(u.DO.Select(conds...))
}

func (u ucSystemMasterRoleRelationDo) Where(conds ...gen.Condition) *ucSystemMasterRoleRelationDo {
	return u.withDO(u.DO.Where(conds...))
}

func (u ucSystemMasterRoleRelationDo) Order(conds ...field.Expr) *ucSystemMasterRoleRelationDo {
	return u.withDO(u.DO.Order(conds...))
}

func (u ucSystemMasterRoleRelationDo) Distinct(cols ...field.Expr) *ucSystemMasterRoleRelationDo {
	return u.withDO(u.DO.Distinct(cols...))
}

func (u ucSystemMasterRoleRelationDo) Omit(cols ...field.Expr) *ucSystemMasterRoleRelationDo {
	return u.withDO(u.DO.Omit(cols...))
}

func (u ucSystemMasterRoleRelationDo) Join(table schema.Tabler, on ...field.Expr) *ucSystemMasterRoleRelationDo {
	return u.withDO(u.DO.Join(table, on...))
}

func (u ucSystemMasterRoleRelationDo) LeftJoin(table schema.Tabler, on ...field.Expr) *ucSystemMasterRoleRelationDo {
	return u.withDO(u.DO.LeftJoin(table, on...))
}

func (u ucSystemMasterRoleRelationDo) RightJoin(table schema.Tabler, on ...field.Expr) *ucSystemMasterRoleRelationDo {
	return u.withDO(u.DO.RightJoin(table, on...))
}

func (u ucSystemMasterRoleRelationDo) Group(cols ...field.Expr) *ucSystemMasterRoleRelationDo {
	return u.withDO(u.DO.Group(cols...))
}

func (u ucSystemMasterRoleRelationDo) Having(conds ...gen.Condition) *ucSystemMasterRoleRelationDo {
	return u.withDO(u.DO.Having(conds...))
}

func (u ucSystemMasterRoleRelationDo) Limit(limit int) *ucSystemMasterRoleRelationDo {
	return u.withDO(u.DO.Limit(limit))
}

func (u ucSystemMasterRoleRelationDo) Offset(offset int) *ucSystemMasterRoleRelationDo {
	return u.withDO(u.DO.Offset(offset))
}

func (u ucSystemMasterRoleRelationDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *ucSystemMasterRoleRelationDo {
	return u.withDO(u.DO.Scopes(funcs...))
}

func (u ucSystemMasterRoleRelationDo) Unscoped() *ucSystemMasterRoleRelationDo {
	return u.withDO(u.DO.Unscoped())
}

func (u ucSystemMasterRoleRelationDo) Create(values ...*model.UcSystemMasterRoleRelation) error {
	if len(values) == 0 {
		return nil
	}
	return u.DO.Create(values)
}

func (u ucSystemMasterRoleRelationDo) CreateInBatches(values []*model.UcSystemMasterRoleRelation, batchSize int) error {
	return u.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (u ucSystemMasterRoleRelationDo) Save(values ...*model.UcSystemMasterRoleRelation) error {
	if len(values) == 0 {
		return nil
	}
	return u.DO.Save(values)
}

func (u ucSystemMasterRoleRelationDo) First() (*model.UcSystemMasterRoleRelation, error) {
	if result, err := u.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.UcSystemMasterRoleRelation), nil
	}
}

func (u ucSystemMasterRoleRelationDo) Take() (*model.UcSystemMasterRoleRelation, error) {
	if result, err := u.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.UcSystemMasterRoleRelation), nil
	}
}

func (u ucSystemMasterRoleRelationDo) Last() (*model.UcSystemMasterRoleRelation, error) {
	if result, err := u.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.UcSystemMasterRoleRelation), nil
	}
}

func (u ucSystemMasterRoleRelationDo) Find() ([]*model.UcSystemMasterRoleRelation, error) {
	result, err := u.DO.Find()
	return result.([]*model.UcSystemMasterRoleRelation), err
}

func (u ucSystemMasterRoleRelationDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.UcSystemMasterRoleRelation, err error) {
	buf := make([]*model.UcSystemMasterRoleRelation, 0, batchSize)
	err = u.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (u ucSystemMasterRoleRelationDo) FindInBatches(result *[]*model.UcSystemMasterRoleRelation, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return u.DO.FindInBatches(result, batchSize, fc)
}

func (u ucSystemMasterRoleRelationDo) Attrs(attrs ...field.AssignExpr) *ucSystemMasterRoleRelationDo {
	return u.withDO(u.DO.Attrs(attrs...))
}

func (u ucSystemMasterRoleRelationDo) Assign(attrs ...field.AssignExpr) *ucSystemMasterRoleRelationDo {
	return u.withDO(u.DO.Assign(attrs...))
}

func (u ucSystemMasterRoleRelationDo) Joins(fields ...field.RelationField) *ucSystemMasterRoleRelationDo {
	for _, _f := range fields {
		u = *u.withDO(u.DO.Joins(_f))
	}
	return &u
}

func (u ucSystemMasterRoleRelationDo) Preload(fields ...field.RelationField) *ucSystemMasterRoleRelationDo {
	for _, _f := range fields {
		u = *u.withDO(u.DO.Preload(_f))
	}
	return &u
}

func (u ucSystemMasterRoleRelationDo) FirstOrInit() (*model.UcSystemMasterRoleRelation, error) {
	if result, err := u.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.UcSystemMasterRoleRelation), nil
	}
}

func (u ucSystemMasterRoleRelationDo) FirstOrCreate() (*model.UcSystemMasterRoleRelation, error) {
	if result, err := u.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.UcSystemMasterRoleRelation), nil
	}
}

func (u ucSystemMasterRoleRelationDo) FindByPage(offset int, limit int) (result []*model.UcSystemMasterRoleRelation, count int64, err error) {
	result, err = u.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = u.Offset(-1).Limit(-1).Count()
	return
}

func (u ucSystemMasterRoleRelationDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = u.Count()
	if err != nil {
		return
	}

	err = u.Offset(offset).Limit(limit).Scan(result)
	return
}

func (u ucSystemMasterRoleRelationDo) Scan(result interface{}) (err error) {
	return u.DO.Scan(result)
}

func (u ucSystemMasterRoleRelationDo) Delete(models ...*model.UcSystemMasterRoleRelation) (result gen.ResultInfo, err error) {
	return u.DO.Delete(models)
}

func (u *ucSystemMasterRoleRelationDo) withDO(do gen.Dao) *ucSystemMasterRoleRelationDo {
	u.DO = *do.(*gen.DO)
	return u
}
