// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"ice_flame_gin/internal/app/models/model"
)

func newUcSystemMasterRole(db *gorm.DB, opts ...gen.DOOption) ucSystemMasterRole {
	_ucSystemMasterRole := ucSystemMasterRole{}

	_ucSystemMasterRole.ucSystemMasterRoleDo.UseDB(db, opts...)
	_ucSystemMasterRole.ucSystemMasterRoleDo.UseModel(&model.UcSystemMasterRole{})

	tableName := _ucSystemMasterRole.ucSystemMasterRoleDo.TableName()
	_ucSystemMasterRole.ALL = field.NewAsterisk(tableName)
	_ucSystemMasterRole.ID = field.NewUint32(tableName, "id")
	_ucSystemMasterRole.Name = field.NewString(tableName, "name")
	_ucSystemMasterRole.Remark = field.NewString(tableName, "remark")
	_ucSystemMasterRole.SupperMaster = field.NewBool(tableName, "supper_master")
	_ucSystemMasterRole.CreatedAt = field.NewTime(tableName, "created_at")
	_ucSystemMasterRole.UpdatedAt = field.NewTime(tableName, "updated_at")

	_ucSystemMasterRole.fillFieldMap()

	return _ucSystemMasterRole
}

// ucSystemMasterRole 管理员角色表
type ucSystemMasterRole struct {
	ucSystemMasterRoleDo ucSystemMasterRoleDo

	ALL          field.Asterisk
	ID           field.Uint32 // 自增ID
	Name         field.String // 角色名称
	Remark       field.String // 备注
	SupperMaster field.Bool   // 1为超级管理员模块
	CreatedAt    field.Time
	UpdatedAt    field.Time

	fieldMap map[string]field.Expr
}

func (u ucSystemMasterRole) Table(newTableName string) *ucSystemMasterRole {
	u.ucSystemMasterRoleDo.UseTable(newTableName)
	return u.updateTableName(newTableName)
}

func (u ucSystemMasterRole) As(alias string) *ucSystemMasterRole {
	u.ucSystemMasterRoleDo.DO = *(u.ucSystemMasterRoleDo.As(alias).(*gen.DO))
	return u.updateTableName(alias)
}

func (u *ucSystemMasterRole) updateTableName(table string) *ucSystemMasterRole {
	u.ALL = field.NewAsterisk(table)
	u.ID = field.NewUint32(table, "id")
	u.Name = field.NewString(table, "name")
	u.Remark = field.NewString(table, "remark")
	u.SupperMaster = field.NewBool(table, "supper_master")
	u.CreatedAt = field.NewTime(table, "created_at")
	u.UpdatedAt = field.NewTime(table, "updated_at")

	u.fillFieldMap()

	return u
}

func (u *ucSystemMasterRole) WithContext(ctx context.Context) *ucSystemMasterRoleDo {
	return u.ucSystemMasterRoleDo.WithContext(ctx)
}

func (u ucSystemMasterRole) TableName() string { return u.ucSystemMasterRoleDo.TableName() }

func (u ucSystemMasterRole) Alias() string { return u.ucSystemMasterRoleDo.Alias() }

func (u ucSystemMasterRole) Columns(cols ...field.Expr) gen.Columns {
	return u.ucSystemMasterRoleDo.Columns(cols...)
}

func (u *ucSystemMasterRole) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := u.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (u *ucSystemMasterRole) fillFieldMap() {
	u.fieldMap = make(map[string]field.Expr, 6)
	u.fieldMap["id"] = u.ID
	u.fieldMap["name"] = u.Name
	u.fieldMap["remark"] = u.Remark
	u.fieldMap["supper_master"] = u.SupperMaster
	u.fieldMap["created_at"] = u.CreatedAt
	u.fieldMap["updated_at"] = u.UpdatedAt
}

func (u ucSystemMasterRole) clone(db *gorm.DB) ucSystemMasterRole {
	u.ucSystemMasterRoleDo.ReplaceConnPool(db.Statement.ConnPool)
	return u
}

func (u ucSystemMasterRole) replaceDB(db *gorm.DB) ucSystemMasterRole {
	u.ucSystemMasterRoleDo.ReplaceDB(db)
	return u
}

type ucSystemMasterRoleDo struct{ gen.DO }

func (u ucSystemMasterRoleDo) Debug() *ucSystemMasterRoleDo {
	return u.withDO(u.DO.Debug())
}

func (u ucSystemMasterRoleDo) WithContext(ctx context.Context) *ucSystemMasterRoleDo {
	return u.withDO(u.DO.WithContext(ctx))
}

func (u ucSystemMasterRoleDo) ReadDB() *ucSystemMasterRoleDo {
	return u.Clauses(dbresolver.Read)
}

func (u ucSystemMasterRoleDo) WriteDB() *ucSystemMasterRoleDo {
	return u.Clauses(dbresolver.Write)
}

func (u ucSystemMasterRoleDo) Session(config *gorm.Session) *ucSystemMasterRoleDo {
	return u.withDO(u.DO.Session(config))
}

func (u ucSystemMasterRoleDo) Clauses(conds ...clause.Expression) *ucSystemMasterRoleDo {
	return u.withDO(u.DO.Clauses(conds...))
}

func (u ucSystemMasterRoleDo) Returning(value interface{}, columns ...string) *ucSystemMasterRoleDo {
	return u.withDO(u.DO.Returning(value, columns...))
}

func (u ucSystemMasterRoleDo) Not(conds ...gen.Condition) *ucSystemMasterRoleDo {
	return u.withDO(u.DO.Not(conds...))
}

func (u ucSystemMasterRoleDo) Or(conds ...gen.Condition) *ucSystemMasterRoleDo {
	return u.withDO(u.DO.Or(conds...))
}

func (u ucSystemMasterRoleDo) Select(conds ...field.Expr) *ucSystemMasterRoleDo {
	return u.withDO(u.DO.Select(conds...))
}

func (u ucSystemMasterRoleDo) Where(conds ...gen.Condition) *ucSystemMasterRoleDo {
	return u.withDO(u.DO.Where(conds...))
}

func (u ucSystemMasterRoleDo) Order(conds ...field.Expr) *ucSystemMasterRoleDo {
	return u.withDO(u.DO.Order(conds...))
}

func (u ucSystemMasterRoleDo) Distinct(cols ...field.Expr) *ucSystemMasterRoleDo {
	return u.withDO(u.DO.Distinct(cols...))
}

func (u ucSystemMasterRoleDo) Omit(cols ...field.Expr) *ucSystemMasterRoleDo {
	return u.withDO(u.DO.Omit(cols...))
}

func (u ucSystemMasterRoleDo) Join(table schema.Tabler, on ...field.Expr) *ucSystemMasterRoleDo {
	return u.withDO(u.DO.Join(table, on...))
}

func (u ucSystemMasterRoleDo) LeftJoin(table schema.Tabler, on ...field.Expr) *ucSystemMasterRoleDo {
	return u.withDO(u.DO.LeftJoin(table, on...))
}

func (u ucSystemMasterRoleDo) RightJoin(table schema.Tabler, on ...field.Expr) *ucSystemMasterRoleDo {
	return u.withDO(u.DO.RightJoin(table, on...))
}

func (u ucSystemMasterRoleDo) Group(cols ...field.Expr) *ucSystemMasterRoleDo {
	return u.withDO(u.DO.Group(cols...))
}

func (u ucSystemMasterRoleDo) Having(conds ...gen.Condition) *ucSystemMasterRoleDo {
	return u.withDO(u.DO.Having(conds...))
}

func (u ucSystemMasterRoleDo) Limit(limit int) *ucSystemMasterRoleDo {
	return u.withDO(u.DO.Limit(limit))
}

func (u ucSystemMasterRoleDo) Offset(offset int) *ucSystemMasterRoleDo {
	return u.withDO(u.DO.Offset(offset))
}

func (u ucSystemMasterRoleDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *ucSystemMasterRoleDo {
	return u.withDO(u.DO.Scopes(funcs...))
}

func (u ucSystemMasterRoleDo) Unscoped() *ucSystemMasterRoleDo {
	return u.withDO(u.DO.Unscoped())
}

func (u ucSystemMasterRoleDo) Create(values ...*model.UcSystemMasterRole) error {
	if len(values) == 0 {
		return nil
	}
	return u.DO.Create(values)
}

func (u ucSystemMasterRoleDo) CreateInBatches(values []*model.UcSystemMasterRole, batchSize int) error {
	return u.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (u ucSystemMasterRoleDo) Save(values ...*model.UcSystemMasterRole) error {
	if len(values) == 0 {
		return nil
	}
	return u.DO.Save(values)
}

func (u ucSystemMasterRoleDo) First() (*model.UcSystemMasterRole, error) {
	if result, err := u.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.UcSystemMasterRole), nil
	}
}

func (u ucSystemMasterRoleDo) Take() (*model.UcSystemMasterRole, error) {
	if result, err := u.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.UcSystemMasterRole), nil
	}
}

func (u ucSystemMasterRoleDo) Last() (*model.UcSystemMasterRole, error) {
	if result, err := u.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.UcSystemMasterRole), nil
	}
}

func (u ucSystemMasterRoleDo) Find() ([]*model.UcSystemMasterRole, error) {
	result, err := u.DO.Find()
	return result.([]*model.UcSystemMasterRole), err
}

func (u ucSystemMasterRoleDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.UcSystemMasterRole, err error) {
	buf := make([]*model.UcSystemMasterRole, 0, batchSize)
	err = u.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (u ucSystemMasterRoleDo) FindInBatches(result *[]*model.UcSystemMasterRole, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return u.DO.FindInBatches(result, batchSize, fc)
}

func (u ucSystemMasterRoleDo) Attrs(attrs ...field.AssignExpr) *ucSystemMasterRoleDo {
	return u.withDO(u.DO.Attrs(attrs...))
}

func (u ucSystemMasterRoleDo) Assign(attrs ...field.AssignExpr) *ucSystemMasterRoleDo {
	return u.withDO(u.DO.Assign(attrs...))
}

func (u ucSystemMasterRoleDo) Joins(fields ...field.RelationField) *ucSystemMasterRoleDo {
	for _, _f := range fields {
		u = *u.withDO(u.DO.Joins(_f))
	}
	return &u
}

func (u ucSystemMasterRoleDo) Preload(fields ...field.RelationField) *ucSystemMasterRoleDo {
	for _, _f := range fields {
		u = *u.withDO(u.DO.Preload(_f))
	}
	return &u
}

func (u ucSystemMasterRoleDo) FirstOrInit() (*model.UcSystemMasterRole, error) {
	if result, err := u.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.UcSystemMasterRole), nil
	}
}

func (u ucSystemMasterRoleDo) FirstOrCreate() (*model.UcSystemMasterRole, error) {
	if result, err := u.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.UcSystemMasterRole), nil
	}
}

func (u ucSystemMasterRoleDo) FindByPage(offset int, limit int) (result []*model.UcSystemMasterRole, count int64, err error) {
	result, err = u.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = u.Offset(-1).Limit(-1).Count()
	return
}

func (u ucSystemMasterRoleDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = u.Count()
	if err != nil {
		return
	}

	err = u.Offset(offset).Limit(limit).Scan(result)
	return
}

func (u ucSystemMasterRoleDo) Scan(result interface{}) (err error) {
	return u.DO.Scan(result)
}

func (u ucSystemMasterRoleDo) Delete(models ...*model.UcSystemMasterRole) (result gen.ResultInfo, err error) {
	return u.DO.Delete(models)
}

func (u *ucSystemMasterRoleDo) withDO(do gen.Dao) *ucSystemMasterRoleDo {
	u.DO = *do.(*gen.DO)
	return u
}
