// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"ice_flame_gin/internal/app/models/model"
)

func newUcSystemMasterVisitCategory(db *gorm.DB, opts ...gen.DOOption) ucSystemMasterVisitCategory {
	_ucSystemMasterVisitCategory := ucSystemMasterVisitCategory{}

	_ucSystemMasterVisitCategory.ucSystemMasterVisitCategoryDo.UseDB(db, opts...)
	_ucSystemMasterVisitCategory.ucSystemMasterVisitCategoryDo.UseModel(&model.UcSystemMasterVisitCategory{})

	tableName := _ucSystemMasterVisitCategory.ucSystemMasterVisitCategoryDo.TableName()
	_ucSystemMasterVisitCategory.ALL = field.NewAsterisk(tableName)
	_ucSystemMasterVisitCategory.ID = field.NewUint32(tableName, "id")
	_ucSystemMasterVisitCategory.Title = field.NewString(tableName, "title")
	_ucSystemMasterVisitCategory.CreatedAt = field.NewTime(tableName, "created_at")
	_ucSystemMasterVisitCategory.UpdatedAt = field.NewTime(tableName, "updated_at")

	_ucSystemMasterVisitCategory.fillFieldMap()

	return _ucSystemMasterVisitCategory
}

// ucSystemMasterVisitCategory 访问类型
type ucSystemMasterVisitCategory struct {
	ucSystemMasterVisitCategoryDo ucSystemMasterVisitCategoryDo

	ALL       field.Asterisk
	ID        field.Uint32 // 自增ID
	Title     field.String // 访问类型标题
	CreatedAt field.Time
	UpdatedAt field.Time

	fieldMap map[string]field.Expr
}

func (u ucSystemMasterVisitCategory) Table(newTableName string) *ucSystemMasterVisitCategory {
	u.ucSystemMasterVisitCategoryDo.UseTable(newTableName)
	return u.updateTableName(newTableName)
}

func (u ucSystemMasterVisitCategory) As(alias string) *ucSystemMasterVisitCategory {
	u.ucSystemMasterVisitCategoryDo.DO = *(u.ucSystemMasterVisitCategoryDo.As(alias).(*gen.DO))
	return u.updateTableName(alias)
}

func (u *ucSystemMasterVisitCategory) updateTableName(table string) *ucSystemMasterVisitCategory {
	u.ALL = field.NewAsterisk(table)
	u.ID = field.NewUint32(table, "id")
	u.Title = field.NewString(table, "title")
	u.CreatedAt = field.NewTime(table, "created_at")
	u.UpdatedAt = field.NewTime(table, "updated_at")

	u.fillFieldMap()

	return u
}

func (u *ucSystemMasterVisitCategory) WithContext(ctx context.Context) *ucSystemMasterVisitCategoryDo {
	return u.ucSystemMasterVisitCategoryDo.WithContext(ctx)
}

func (u ucSystemMasterVisitCategory) TableName() string {
	return u.ucSystemMasterVisitCategoryDo.TableName()
}

func (u ucSystemMasterVisitCategory) Alias() string { return u.ucSystemMasterVisitCategoryDo.Alias() }

func (u ucSystemMasterVisitCategory) Columns(cols ...field.Expr) gen.Columns {
	return u.ucSystemMasterVisitCategoryDo.Columns(cols...)
}

func (u *ucSystemMasterVisitCategory) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := u.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (u *ucSystemMasterVisitCategory) fillFieldMap() {
	u.fieldMap = make(map[string]field.Expr, 4)
	u.fieldMap["id"] = u.ID
	u.fieldMap["title"] = u.Title
	u.fieldMap["created_at"] = u.CreatedAt
	u.fieldMap["updated_at"] = u.UpdatedAt
}

func (u ucSystemMasterVisitCategory) clone(db *gorm.DB) ucSystemMasterVisitCategory {
	u.ucSystemMasterVisitCategoryDo.ReplaceConnPool(db.Statement.ConnPool)
	return u
}

func (u ucSystemMasterVisitCategory) replaceDB(db *gorm.DB) ucSystemMasterVisitCategory {
	u.ucSystemMasterVisitCategoryDo.ReplaceDB(db)
	return u
}

type ucSystemMasterVisitCategoryDo struct{ gen.DO }

func (u ucSystemMasterVisitCategoryDo) Debug() *ucSystemMasterVisitCategoryDo {
	return u.withDO(u.DO.Debug())
}

func (u ucSystemMasterVisitCategoryDo) WithContext(ctx context.Context) *ucSystemMasterVisitCategoryDo {
	return u.withDO(u.DO.WithContext(ctx))
}

func (u ucSystemMasterVisitCategoryDo) ReadDB() *ucSystemMasterVisitCategoryDo {
	return u.Clauses(dbresolver.Read)
}

func (u ucSystemMasterVisitCategoryDo) WriteDB() *ucSystemMasterVisitCategoryDo {
	return u.Clauses(dbresolver.Write)
}

func (u ucSystemMasterVisitCategoryDo) Session(config *gorm.Session) *ucSystemMasterVisitCategoryDo {
	return u.withDO(u.DO.Session(config))
}

func (u ucSystemMasterVisitCategoryDo) Clauses(conds ...clause.Expression) *ucSystemMasterVisitCategoryDo {
	return u.withDO(u.DO.Clauses(conds...))
}

func (u ucSystemMasterVisitCategoryDo) Returning(value interface{}, columns ...string) *ucSystemMasterVisitCategoryDo {
	return u.withDO(u.DO.Returning(value, columns...))
}

func (u ucSystemMasterVisitCategoryDo) Not(conds ...gen.Condition) *ucSystemMasterVisitCategoryDo {
	return u.withDO(u.DO.Not(conds...))
}

func (u ucSystemMasterVisitCategoryDo) Or(conds ...gen.Condition) *ucSystemMasterVisitCategoryDo {
	return u.withDO(u.DO.Or(conds...))
}

func (u ucSystemMasterVisitCategoryDo) Select(conds ...field.Expr) *ucSystemMasterVisitCategoryDo {
	return u.withDO(u.DO.Select(conds...))
}

func (u ucSystemMasterVisitCategoryDo) Where(conds ...gen.Condition) *ucSystemMasterVisitCategoryDo {
	return u.withDO(u.DO.Where(conds...))
}

func (u ucSystemMasterVisitCategoryDo) Order(conds ...field.Expr) *ucSystemMasterVisitCategoryDo {
	return u.withDO(u.DO.Order(conds...))
}

func (u ucSystemMasterVisitCategoryDo) Distinct(cols ...field.Expr) *ucSystemMasterVisitCategoryDo {
	return u.withDO(u.DO.Distinct(cols...))
}

func (u ucSystemMasterVisitCategoryDo) Omit(cols ...field.Expr) *ucSystemMasterVisitCategoryDo {
	return u.withDO(u.DO.Omit(cols...))
}

func (u ucSystemMasterVisitCategoryDo) Join(table schema.Tabler, on ...field.Expr) *ucSystemMasterVisitCategoryDo {
	return u.withDO(u.DO.Join(table, on...))
}

func (u ucSystemMasterVisitCategoryDo) LeftJoin(table schema.Tabler, on ...field.Expr) *ucSystemMasterVisitCategoryDo {
	return u.withDO(u.DO.LeftJoin(table, on...))
}

func (u ucSystemMasterVisitCategoryDo) RightJoin(table schema.Tabler, on ...field.Expr) *ucSystemMasterVisitCategoryDo {
	return u.withDO(u.DO.RightJoin(table, on...))
}

func (u ucSystemMasterVisitCategoryDo) Group(cols ...field.Expr) *ucSystemMasterVisitCategoryDo {
	return u.withDO(u.DO.Group(cols...))
}

func (u ucSystemMasterVisitCategoryDo) Having(conds ...gen.Condition) *ucSystemMasterVisitCategoryDo {
	return u.withDO(u.DO.Having(conds...))
}

func (u ucSystemMasterVisitCategoryDo) Limit(limit int) *ucSystemMasterVisitCategoryDo {
	return u.withDO(u.DO.Limit(limit))
}

func (u ucSystemMasterVisitCategoryDo) Offset(offset int) *ucSystemMasterVisitCategoryDo {
	return u.withDO(u.DO.Offset(offset))
}

func (u ucSystemMasterVisitCategoryDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *ucSystemMasterVisitCategoryDo {
	return u.withDO(u.DO.Scopes(funcs...))
}

func (u ucSystemMasterVisitCategoryDo) Unscoped() *ucSystemMasterVisitCategoryDo {
	return u.withDO(u.DO.Unscoped())
}

func (u ucSystemMasterVisitCategoryDo) Create(values ...*model.UcSystemMasterVisitCategory) error {
	if len(values) == 0 {
		return nil
	}
	return u.DO.Create(values)
}

func (u ucSystemMasterVisitCategoryDo) CreateInBatches(values []*model.UcSystemMasterVisitCategory, batchSize int) error {
	return u.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (u ucSystemMasterVisitCategoryDo) Save(values ...*model.UcSystemMasterVisitCategory) error {
	if len(values) == 0 {
		return nil
	}
	return u.DO.Save(values)
}

func (u ucSystemMasterVisitCategoryDo) First() (*model.UcSystemMasterVisitCategory, error) {
	if result, err := u.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.UcSystemMasterVisitCategory), nil
	}
}

func (u ucSystemMasterVisitCategoryDo) Take() (*model.UcSystemMasterVisitCategory, error) {
	if result, err := u.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.UcSystemMasterVisitCategory), nil
	}
}

func (u ucSystemMasterVisitCategoryDo) Last() (*model.UcSystemMasterVisitCategory, error) {
	if result, err := u.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.UcSystemMasterVisitCategory), nil
	}
}

func (u ucSystemMasterVisitCategoryDo) Find() ([]*model.UcSystemMasterVisitCategory, error) {
	result, err := u.DO.Find()
	return result.([]*model.UcSystemMasterVisitCategory), err
}

func (u ucSystemMasterVisitCategoryDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.UcSystemMasterVisitCategory, err error) {
	buf := make([]*model.UcSystemMasterVisitCategory, 0, batchSize)
	err = u.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (u ucSystemMasterVisitCategoryDo) FindInBatches(result *[]*model.UcSystemMasterVisitCategory, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return u.DO.FindInBatches(result, batchSize, fc)
}

func (u ucSystemMasterVisitCategoryDo) Attrs(attrs ...field.AssignExpr) *ucSystemMasterVisitCategoryDo {
	return u.withDO(u.DO.Attrs(attrs...))
}

func (u ucSystemMasterVisitCategoryDo) Assign(attrs ...field.AssignExpr) *ucSystemMasterVisitCategoryDo {
	return u.withDO(u.DO.Assign(attrs...))
}

func (u ucSystemMasterVisitCategoryDo) Joins(fields ...field.RelationField) *ucSystemMasterVisitCategoryDo {
	for _, _f := range fields {
		u = *u.withDO(u.DO.Joins(_f))
	}
	return &u
}

func (u ucSystemMasterVisitCategoryDo) Preload(fields ...field.RelationField) *ucSystemMasterVisitCategoryDo {
	for _, _f := range fields {
		u = *u.withDO(u.DO.Preload(_f))
	}
	return &u
}

func (u ucSystemMasterVisitCategoryDo) FirstOrInit() (*model.UcSystemMasterVisitCategory, error) {
	if result, err := u.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.UcSystemMasterVisitCategory), nil
	}
}

func (u ucSystemMasterVisitCategoryDo) FirstOrCreate() (*model.UcSystemMasterVisitCategory, error) {
	if result, err := u.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.UcSystemMasterVisitCategory), nil
	}
}

func (u ucSystemMasterVisitCategoryDo) FindByPage(offset int, limit int) (result []*model.UcSystemMasterVisitCategory, count int64, err error) {
	result, err = u.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = u.Offset(-1).Limit(-1).Count()
	return
}

func (u ucSystemMasterVisitCategoryDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = u.Count()
	if err != nil {
		return
	}

	err = u.Offset(offset).Limit(limit).Scan(result)
	return
}

func (u ucSystemMasterVisitCategoryDo) Scan(result interface{}) (err error) {
	return u.DO.Scan(result)
}

func (u ucSystemMasterVisitCategoryDo) Delete(models ...*model.UcSystemMasterVisitCategory) (result gen.ResultInfo, err error) {
	return u.DO.Delete(models)
}

func (u *ucSystemMasterVisitCategoryDo) withDO(do gen.Dao) *ucSystemMasterVisitCategoryDo {
	u.DO = *do.(*gen.DO)
	return u
}
